#if canImport(Darwin)
import XCTest
import Foundation
import XPCCodable

/// Not generated by anything. An ordinary `@objc` protocol of the sort an
/// existing NSXPC codebase is already full of.
@objc protocol Printer {
    func print(_ line: String)
    func pages(reply: @escaping (NSNumber?, (any Error)?) -> Void)
}

private final class PrinterImpl: NSObject, Printer, @unchecked Sendable {
    var lines: [String] = []
    func print(_ line: String) { lines.append(line) }
    func pages(reply: @escaping (NSNumber?, (any Error)?) -> Void) {
        reply(NSNumber(value: lines.count), nil)
    }
}

@XPCService
protocol Spooler {
    func bind(_ printer: XPCProxyMarker<Printer>)
    func emit(_ printer: XPCProxyMarker<Printer>, line: String) async throws -> Int
}

private final class SpoolerImpl: Spooler, @unchecked Sendable {
    func bind(_ printer: XPCProxyMarker<Printer>) {}
    func emit(_ printer: XPCProxyMarker<Printer>, line: String) async throws -> Int {
        printer.wrappedValue.print(line)
        return try await withCheckedThrowingContinuation { continuation in
            printer.wrappedValue.pages { count, error in
                if let error { continuation.resume(throwing: error) }
                else { continuation.resume(returning: count?.intValue ?? -1) }
            }
        }
    }
}

private final class Delegate: NSObject, NSXPCListenerDelegate {
    func listener(_ listener: NSXPCListener,
                  shouldAcceptNewConnection connection: NSXPCConnection) -> Bool {
        connection.exportedInterface = SpoolerXPC.interface
        connection.exportedObject = SpoolerXPC.exported(SpoolerImpl())
        connection.resume()
        return true
    }
}

/// The point of constraining `XPCProxyMarker` to `AnyObject`: what it admits is
/// exactly what NSXPC can vend, so an `@objc` protocol nobody generated works
/// with no wrapping at all.
final class ObjCProxyMarkerTests: XCTestCase {

    private var listener: NSXPCListener!
    private var delegate: Delegate!
    private var connection: NSXPCConnection!

    override func setUp() {
        super.setUp()
        listener = NSXPCListener.anonymous()
        delegate = Delegate()
        listener.delegate = delegate
        listener.resume()

        connection = NSXPCConnection(listenerEndpoint: listener.endpoint)
        connection.remoteObjectInterface = SpoolerXPC.interface
        connection.resume()
    }

    override func tearDown() {
        connection.invalidate()
        listener.invalidate()
        super.tearDown()
    }

    func testTheProtocolItselfIsTheInterfaceRegistered() {
        let nested = SpoolerXPC.interface.forSelector(
            NSSelectorFromString("bind:"), argumentIndex: 0, ofReply: false)
        // Its own name, not a generated shim's: nothing was generated for it.
        XCTAssertEqual(nested.map { NSStringFromProtocol($0.protocol) },
                       "XPCCodableTests.Printer")
    }

    func testAHandWrittenObjCProtocolCrossesAsAProxy() async throws {
        let printer = PrinterImpl()
        let pages = try await SpoolerXPC.remote(connection).emit(printer, line: "hello")

        XCTAssertEqual(pages, 1, "the service should have called back into our printer")
        XCTAssertEqual(printer.lines, ["hello"])
    }

    /// What the constraint rejects, and why it is worth having.
    ///
    /// `Service: AnyObject` admits an `@objc` protocol's existential — those
    /// self-conform and are class-bound — and a class. It rejects a plain Swift
    /// protocol whether or not it is refined by `AnyObject`, and rejects a
    /// struct. Measured; none of these compile:
    ///
    ///     protocol Plain {}                    // XPCProxyMarker<Plain>
    ///     protocol Bound: AnyObject {}         // XPCProxyMarker<Bound>
    ///     struct Value {}                      // XPCProxyMarker<Value>
    ///
    /// That is why a Swift-native `@XPCService` protocol is named by its
    /// generated shim rather than directly — see `ProxyMarkerTests`.
    func testWhatTheConstraintRejects() {}
}
#endif
